### ISSUE TITLE
The input tensor shape of the self-attention in decoder when doing the beam search 

### ISSUE THREAD

**Issue by jlxy** [aimagelab/meshed-memory-transformer#28]
Hello! Thank you for providing this good work.
When I run _evaluate_metrics_ function in train.py (it's actually doing the beam search), I found that, at each time step, the input tensor shape of _MeshedDecoderLayer_ is (10, 1, 512), where 10 is the batch size and 512 is d_model. 
Why the shape isn't (10, t, 512)? Here, t is the number of time step. By inputting this (10, t, 512)-shaped  tensor, the decoder can make use of information from all previous time steps instead of only the last time step. And in my opinion, this is also how Transformer works.

**Comment by baraldilorenzo** [comment]
Hi @jlxy,

you are right about the shape of the input tensor during beam search. Inside the model we have a caching mechanism that saves the attention states of the previous inputs, so that at each timestep we only need to feed the new input. This saves (a lot) of computation and makes beam search faster. You might find more about this in the `statefulness` context manager we define in our `Module` class (https://github.com/aimagelab/meshed-memory-transformer/blob/master/models/containers.py). This is then used to store, for instance, previous keys and values in the attention layer (cfr. https://github.com/aimagelab/meshed-memory-transformer/blob/master/models/transformer/attention.py#L167).

Let me know if you need further explanation on this.

Best,
Lorenzo.
