### ISSUE TITLE
features (N, 2048) = graph node features? & How to switch "mode='teacher_forcing" to mode='feedback'  when testing

### ISSUE THREAD

**Issue by XuMengyaAmy** [aimagelab/meshed-memory-transformer#33]
Thanks for your quick response before! It's really helpful! I have some other questions. Hope you can kindly help me. (That issue is closed.)
1) The features (N, 2048) for each image in coco_detections.hdf5 are graph node features. You didn't use the whole image as a context. Is it correct? 
2) From my understanding, Mk, Mv are related with "the priori knowledge on relationships between image regions"?
3) I try to save the predicted caption "json.dump(gen, open('predict_caption/predict_caption_val.json', 'w'))". Have you ever encountered the problem that all the predicted captions are the same sentence?
4) During training, we use teacher forcing and feed the true word in the next time step. During testing though, we have to feed the predicted word to generate the sentence. In the code, I saw "mode='teacher_forcing", mode='feedback'. But how you switch them between training and testing?
5) If you don’t mind, could you publish the script for "visualization of attention states" (Integrated Gradients approach)?

**Comment by marcellacornia** [comment]
Hi @XuMengyaAmy,

1) Yes, we only used the image region features coming from Faster R-CNN trained on Visual Genome. We did not use any additional features to represent the global image.
2) The Mk and Mv are additional vectors learned during training that can represent the intrinsic relationships between image regions.
3) This is not possible. The generated captions change according to the images given as input to the model.
4) When you call the model.forward, the model uses the ground-truth words. When you call the model.beam_search instead, the model uses the previously generated words.
5) Since we are currently working on different projects, we do not plan to release the script at the moment. 

Hope this answers all your questions.

Best,
Marcella
