### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 74570219520, sblock->base_addr = 0, stored_eof = 74924166416)

### ISSUE THREAD

**Issue by HHeracles** [aimagelab/meshed-memory-transformer#64]
The structure of data directory is:
dataset
├── annotations
│ ├── captions_train2014.json
│ ├── captions_val2014.json
│ ├── coco_dev_ids.npy
│ ├── IIIT5k_3000
│ ├── coco_restval_ids.npy
│ ├── coco_test_ids.npy
│ └── coco_train_ids.npy
├── feature
│ ├── coco_all_align.hdf5
And to train your model with the parameters used in our experiments, use:

CUDA_VISIBLE_DEVICES=0,1 python train.py --exp_name m2_transformer --batch_size 8 --m 40 --head 8 --warmup 10000 --features_path dataset/feature/coco_all_align.hdf5 --annotation_folder dataset/annotations
I get the error as follow:
![image](https://user-images.githubusercontent.com/42307937/132194666-a9f4da6d-55ff-4b9a-bf71-dcca572bb56b.png)
Why did this error happen? How to solve it?Thank you!

**Comment by wlcosta** [comment]
This error happened to me because my file was corrupted. From the file's `eof` and its `stored_eof`, it appears that your download corrupted the last part of the file. You could try downloading it again.

My MD5 checksum for `coco_detections.hdf5` is `695f3eddea88f2f5f7f47febf11e2de2` in case you want to check yours too.
